import { cyan, dim, info, ok, warn } from '../output.ts';
import { starshipConfig, tildify } from '../paths.ts';
import { starshipSnippet } from '../shell/assets.ts';

const TOML_BEGIN = '# >>> b (path bookmarks) >>>';
const TOML_END = '# <<< b (path bookmarks) <<<';

/**
 * Add the prompt segment to starship's config. Kept behind a flag: the file may
 * be generated by another tool, in which case our block gets overwritten.
 */
export function patchStarship(dryRun: boolean): void {
    const file = starshipConfig();
    let text = '';
    let existed = true;
    try {
        text = Deno.readTextFileSync(file);
    } catch {
        existed = false;
    }
    if (!existed) {
        warn(`no starship config at ${tildify(file)} — skipping`);
        return;
    }

    const start = text.indexOf(TOML_BEGIN);
    let next: string;
    if (start === -1) {
        const sep = text.endsWith('\n') ? '' : '\n';
        next = `${text}${sep}\n${starshipSnippet()}`;
    } else {
        const endIdx = text.indexOf(TOML_END, start);
        const stop = endIdx === -1 ? text.length : endIdx + TOML_END.length;
        next =
            text.slice(0, start) +
            starshipSnippet().replace(/\n$/, '') +
            text.slice(stop);
    }

    if (next === text) {
        ok(`${cyan(tildify(file))} already has the prompt segment`);
    } else if (dryRun) {
        info(
            `  ${dim(`would ${start === -1 ? 'append' : 'update'} the b block in ${tildify(file)}`)}`,
        );
    } else {
        try {
            Deno.writeTextFileSync(file, next);
        } catch {
            warn(
                `cannot write ${tildify(file)} — re-run ${cyan('b setup')} to widen permissions`,
            );
            return;
        }
        ok(
            `${start === -1 ? 'added' : 'updated'} the prompt segment in ${cyan(tildify(file))}`,
        );
    }

    if (/^# generated by/m.test(text)) {
        warn(
            `${tildify(file)} looks generated — regenerating it will drop this block`,
        );
    }
    // Only a top-level format hides the segment; modules have their own `format`.
    const topLevel = text.split(/^\s*\[/m)[0] ?? '';
    if (/^\s*format\s*=/m.test(topLevel)) {
        info(
            `  ${dim('that config pins a top-level `format`, so add `$env_var` where you want the segment')}`,
        );
    }
}
