# b — path bookmarks with contexts. Generated by `b setup`; edits are lost on
# the next run. Sourced from ~/.zshrc.

# An existing `b` alias (the older cd_mark helper, for one) turns the function
# definition below into a parse error, so clear it first.
unalias b 2>/dev/null

typeset -g _b_ctx_dir="${XDG_CONFIG_HOME:-$HOME/.config}/b/ctx"
[[ -d $_b_ctx_dir ]] || mkdir -p $_b_ctx_dir 2>/dev/null

# A context is a bookmark plus the directory you were last at inside it.
# Recording that on every cd has to stay in-shell: spawning the binary would
# add ~35ms to each prompt. Leaving the bookmark's subtree ends the context.
_b_chpwd() {
  [[ -n $B_CTX && -n $B_CTX_ROOT ]] || return 0
  if [[ $PWD == $B_CTX_ROOT || $PWD == ${B_CTX_ROOT%/}/* ]]; then
    print -r -- $PWD >| $_b_ctx_dir/$B_CTX 2>/dev/null
  else
    export B_CTX_PREV=$B_CTX
    unset B_CTX B_CTX_ROOT
  fi
}
autoload -Uz add-zsh-hook
add-zsh-hook chpwd _b_chpwd

# The binary cannot change the parent shell's directory or environment, so this
# wrapper does. With --from-shell the binary answers a request with a $'\x01b2'
# header followed by `cd:`, `ctx:`, `root:` and `prev:` lines. Anything else is ordinary
# output and gets reprinted verbatim.
b() {
  emulate -L zsh
  setopt local_options no_nomatch

  if [[ $# -eq 1 && $1 == - ]]; then
    cd -
    return $?
  fi

  local tty=0
  [[ -t 1 ]] && tty=1

  local out ret
  out="$(B_TTY=$tty command b --from-shell "$@")"
  ret=$?

  if [[ ${out%%$'\n'*} != $'\x01b2' ]]; then
    [[ -n $out ]] && print -r -- "$out"
    return $ret
  fi

  local -a lines
  lines=("${(@f)out}")
  shift lines

  local target='' ctx='' root='' prev='' has_cd=0 has_ctx=0 has_prev=0 l
  for l in "${lines[@]}"; do
    case $l in
      (cd:*)   target=${l#cd:};   has_cd=1 ;;
      (ctx:*)  ctx=${l#ctx:};     has_ctx=1 ;;
      (root:*) root=${l#root:} ;;
      (prev:*) prev=${l#prev:};   has_prev=1 ;;
    esac
  done

  # Apply the context before moving, so the chpwd hook above credits the new
  # context rather than the one being left behind.
  local old_ctx=$B_CTX old_root=$B_CTX_ROOT old_prev=$B_CTX_PREV
  if (( has_ctx )); then
    [[ -n $B_CTX && $B_CTX != $ctx ]] && export B_CTX_PREV=$B_CTX
    if [[ -n $ctx ]]; then
      # Nothing to go back to when the previous context is the one being entered.
      [[ $B_CTX_PREV == $ctx ]] && unset B_CTX_PREV
      export B_CTX=$ctx B_CTX_ROOT=$root
    else
      unset B_CTX B_CTX_ROOT
    fi
  fi
  # An explicit previous context (after a rename or removal) overrides the above.
  if (( has_prev )); then
    if [[ -n $prev ]]; then
      export B_CTX_PREV=$prev
    else
      unset B_CTX_PREV
    fi
  fi

  if (( has_cd )); then
    if ! cd -- "$target"; then
      if (( has_ctx || has_prev )); then
        if [[ -n $old_ctx ]]; then
          export B_CTX=$old_ctx B_CTX_ROOT=$old_root
        else
          unset B_CTX B_CTX_ROOT
        fi
        if [[ -n $old_prev ]]; then
          export B_CTX_PREV=$old_prev
        else
          unset B_CTX_PREV
        fi
      fi
      return 1
    fi
  elif (( has_ctx )); then
    # No move, but the context changed: refresh its memory for this directory.
    _b_chpwd
  fi
  return 0
}

# Completion is delegated to the binary: it reports the candidates plus how to
# render them, so this function never has to know about the command surface.
_b() {
  # No `emulate -L zsh` here: the completion system already sets the options
  # helpers like _files and _describe rely on (extended_glob in particular).
  local -a lines
  lines=("${(@f)$(command b __complete "$CURRENT" "${(@)words}" 2>/dev/null)}")
  (( ${#lines} )) || return 1

  local mode=${lines[1]#@mode:}
  shift lines

  case $mode in
    none)
      return 1
      ;;

    dirs)
      _files -/
      return
      ;;

    paths)
      # @strip:<n> says how many leading characters of the word are already
      # settled, so only the tail is listed and matched.
      local -a vals
      local l strip=0
      for l in "${lines[@]}"; do
        if [[ $l == @strip:* ]]; then
          strip=${l#@strip:}
          continue
        fi
        [[ -z $l || $l == @* ]] && continue
        vals+=("${l%%$'\t'*}")
      done
      (( ${#vals} )) || return 1
      (( strip )) && compset -p $strip
      compadd -S '' -- "${vals[@]}"
      return
      ;;
  esac

  # describe: candidates arrive in @group blocks so zsh can show headings.
  local ret=1 tag='' label='' l rest
  local -a cands
  lines+=('@group:__flush__:')
  for l in "${lines[@]}"; do
    if [[ $l == @group:* ]]; then
      if (( ${#cands} )); then
        # Values that begin with a dash need -o, or _describe drops them.
        if [[ $tag == options ]]; then
          _describe -o -t "$tag" "$label" cands && ret=0
        else
          _describe -t "$tag" "$label" cands && ret=0
        fi
        cands=()
      fi
      rest=${l#@group:}
      tag=${rest%%:*}
      label=${rest#*:}
      continue
    fi
    [[ -z $l || $l == @* ]] && continue
    # _describe splits on the first unescaped colon.
    cands+=("${${l%%$'\t'*}//:/\\:}:${l#*$'\t'}")
  done

  return $ret
}

if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit -C
fi
compdef _b b

# Scoped to `b` only, so a global completion setup stays untouched: show the
# bookmark and command groups under their own headings instead of one flat list.
zstyle ':completion:*:*:b:*' group-name ''
zstyle ':completion:*:*:b:*:descriptions' format '%F{244}%d%f'
