import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bold, cyan, dim, fail, info, ok, UserError, warn } from './output.ts';
import {
    bookmarksFile,
    configDir,
    homedir,
    initFile,
    markNames,
    marksDir,
    starshipConfig,
    tildify,
    zshrc,
} from './paths.ts';
import INIT_ZSH from './shell/init.zsh' with { type: 'text' };
import STARSHIP_BLOCK from './shell/starship.toml' with { type: 'text' };
import { load } from './store.ts';

const BEGIN = '# >>> b (path bookmarks) >>>';
const END = '# <<< b (path bookmarks) <<<';

export function shellInit(): string {
    return INIT_ZSH;
}

export function starshipSnippet(): string {
    return STARSHIP_BLOCK;
}

const TOML_BEGIN = '# >>> b (path bookmarks) >>>';
const TOML_END = '# <<< b (path bookmarks) <<<';

/**
 * Add the prompt segment to starship's config. Kept behind a flag: the file may
 * be generated by another tool, in which case our block gets overwritten.
 */
export function patchStarship(dryRun: boolean): void {
    const file = starshipConfig();
    let text = '';
    let existed = true;
    try {
        text = Deno.readTextFileSync(file);
    } catch {
        existed = false;
    }
    if (!existed) {
        warn(`no starship config at ${tildify(file)} — skipping`);
        return;
    }

    const start = text.indexOf(TOML_BEGIN);
    let next: string;
    if (start === -1) {
        const sep = text.endsWith('\n') ? '' : '\n';
        next = `${text}${sep}\n${starshipSnippet()}`;
    } else {
        const endIdx = text.indexOf(TOML_END, start);
        const stop = endIdx === -1 ? text.length : endIdx + TOML_END.length;
        next =
            text.slice(0, start) +
            starshipSnippet().replace(/\n$/, '') +
            text.slice(stop);
    }

    if (next === text) {
        ok(`${cyan(tildify(file))} already has the prompt segment`);
    } else if (dryRun) {
        info(
            `  ${dim(`would ${start === -1 ? 'append' : 'update'} the b block in ${tildify(file)}`)}`,
        );
    } else {
        try {
            Deno.writeTextFileSync(file, next);
        } catch {
            warn(
                `cannot write ${tildify(file)} — re-run ${cyan('b setup')} to widen permissions`,
            );
            return;
        }
        ok(
            `${start === -1 ? 'added' : 'updated'} the prompt segment in ${cyan(tildify(file))}`,
        );
    }

    if (/^# generated by/m.test(text)) {
        warn(
            `${tildify(file)} looks generated — regenerating it will drop this block`,
        );
    }
    if (/^format\s*=/m.test(text)) {
        info(
            `  ${dim('that config pins a top-level `format`, so add `$env_var` where you want the segment')}`,
        );
    }
}

/** ~/x → $HOME/x so the generated snippet survives a moved home dir. */
function homeRef(p: string): string {
    const t = tildify(p);
    return t.startsWith('~') ? `$HOME${t.slice(1)}` : p;
}

function homeVar(p: string): string {
    return `"${homeRef(p)}"`;
}

function denoBinDir(): string {
    const root = Deno.env.get('DENO_INSTALL_ROOT');
    return join(
        root && root.length > 0 ? root : join(homedir(), '.deno'),
        'bin',
    );
}

function onPath(dir: string): boolean {
    return (Deno.env.get('PATH') ?? '').split(':').includes(dir);
}

function exists(p: string): boolean {
    try {
        Deno.statSync(p);
        return true;
    } catch {
        return false;
    }
}

function rcBlock(needPath: boolean, binDir: string): string {
    const lines = [BEGIN];
    if (needPath) lines.push(`export PATH="${homeRef(binDir)}:$PATH"`);
    lines.push(
        `[[ -f ${homeVar(initFile())} ]] && source ${homeVar(initFile())}`,
    );
    lines.push(END);
    return lines.join('\n');
}

type RcState = { text: string; hasBlock: boolean };

function readRc(): RcState {
    try {
        const text = Deno.readTextFileSync(zshrc());
        return { text, hasBlock: text.includes(BEGIN) };
    } catch (err) {
        if (err instanceof Deno.errors.NotFound)
            return { text: '', hasBlock: false };
        throw err;
    }
}

/** The existing managed block, or "" when there is none. */
function currentBlock(text: string): string {
    const start = text.indexOf(BEGIN);
    if (start === -1) return '';
    const endIdx = text.indexOf(END, start);
    return text.slice(start, endIdx === -1 ? text.length : endIdx + END.length);
}

function replaceBlock(text: string, block: string | null): string {
    const start = text.indexOf(BEGIN);
    if (start === -1) {
        if (block === null) return text;
        const sep = text.length === 0 || text.endsWith('\n') ? '' : '\n';
        return `${text}${sep}\n${block}\n`;
    }
    const endIdx = text.indexOf(END, start);
    const stop = endIdx === -1 ? text.length : endIdx + END.length;
    let head = text.slice(0, start);
    const tail = text.slice(stop).replace(/^\n/, '');
    if (block === null) {
        head = head.replace(/\n+$/, '\n');
        return head + tail;
    }
    return `${head}${block}\n${tail}`;
}

/** Reinstall the global shim so `command b` exists and points at this source. */
async function installBinary(entry: string, dryRun: boolean): Promise<string> {
    const write = `--allow-write=${configDir()},${zshrc()},${starshipConfig()}`;
    const args = [
        'install',
        '-g',
        '-f',
        '-q',
        '--allow-read',
        write,
        '--allow-env',
        '--allow-run=deno',
        '-n',
        'b',
        entry,
    ];
    if (dryRun) {
        info(`  ${dim(`would run: deno ${args.join(' ')}`)}`);
        return join(denoBinDir(), 'b');
    }
    // Spawn by name, not Deno.execPath(): --allow-run=deno matches the name, and
    // the resolved binary can be a symlink the allowlist would reject.
    const status = await new Deno.Command('deno', {
        args,
        stdout: 'inherit',
        stderr: 'inherit',
    }).output();
    if (!status.success) {
        throw new UserError('`deno install -g` failed — see the output above');
    }
    return join(denoBinDir(), 'b');
}

export type SetupOptions = {
    dryRun: boolean;
    remove: boolean;
    force: boolean;
    starship: boolean;
};

export async function setup(opts: SetupOptions): Promise<number> {
    if (Deno.build.os === 'windows')
        throw new UserError('only zsh on macOS/Linux is supported so far');

    const rcPath = zshrc();

    if (opts.remove) {
        const rc = readRc();
        if (!rc.hasBlock) {
            warn(`no b block found in ${tildify(rcPath)} — nothing to remove`);
        } else if (opts.dryRun) {
            info(
                `  ${dim(`would remove the b block from ${tildify(rcPath)}`)}`,
            );
        } else {
            Deno.writeTextFileSync(rcPath, replaceBlock(rc.text, null));
            ok(`removed the b block from ${tildify(rcPath)}`);
        }
        info('');
        info(`Bookmarks are kept at ${cyan(tildify(bookmarksFile()))}.`);
        info(`Remove the command with ${cyan('deno uninstall -g b')}.`);
        return 0;
    }

    info(bold('Setting up b for zsh'));
    info('');

    // 1. global shim
    const entry = fileURLToPath(new URL('./cli.ts', import.meta.url));
    const binPath = await installBinary(entry, opts.dryRun);
    ok(`command installed at ${cyan(tildify(binPath))}`);
    info(`  ${dim(`runs ${tildify(entry)} — keep this project on disk`)}`);

    // 2. shell integration file
    const init = initFile();
    if (opts.dryRun) {
        info(`  ${dim(`would write ${tildify(init)}`)}`);
    } else {
        Deno.mkdirSync(configDir(), { recursive: true });
        Deno.writeTextFileSync(init, shellInit());
    }
    ok(`shell integration written to ${cyan(tildify(init))}`);

    // 3. ~/.zshrc hook
    const binDir = denoBinDir();
    const rc = readRc();
    // Once the block puts binDir on $PATH, $PATH contains it on every later run —
    // so keep the line rather than "helpfully" dropping it again.
    const needPath =
        !onPath(binDir) || /^export PATH=/m.test(currentBlock(rc.text));
    const block = rcBlock(needPath, binDir);
    const next = replaceBlock(rc.text, block);

    if (next === rc.text && !opts.force) {
        ok(`${cyan(tildify(rcPath))} already sources it`);
    } else if (opts.dryRun) {
        info(
            `  ${dim(`would ${rc.hasBlock ? 'update' : 'append'} the b block in ${tildify(rcPath)}`)}`,
        );
        for (const line of block.split('\n')) info(`  ${dim(`| ${line}`)}`);
    } else {
        Deno.writeTextFileSync(rcPath, next);
        ok(
            `${rc.hasBlock ? 'updated' : 'appended'} the b block in ${cyan(tildify(rcPath))}`,
        );
    }
    if (needPath)
        info(`  ${dim(`the block also puts ${tildify(binDir)} on $PATH`)}`);

    // 4. optional starship prompt segment
    if (opts.starship) patchStarship(opts.dryRun);

    info('');
    if (opts.dryRun) {
        info(`Dry run — nothing changed. Re-run ${cyan('b setup')} to apply.`);
        return 0;
    }
    info(bold('One last step:'));
    info(`  ${cyan('exec zsh')}   ${dim('# reload this shell')}`);
    info('');
    info(`Then try: ${cyan('b add')} here, ${cyan('b <TAB>')} to jump.`);
    // Only nag about the old cd_mark store while something in it is still missing.
    let pending = 0;
    try {
        const known = load().bookmarks;
        pending = markNames().filter((n) => {
            return !Object.hasOwn(known, n);
        }).length;
    } catch {
        pending = 0;
    }
    if (pending > 0) {
        info(
            `${pending} bookmark${pending === 1 ? '' : 's'} in ${tildify(marksDir())} ` +
                `${pending === 1 ? 'is' : 'are'} not imported yet — run ${cyan('b import')}.`,
        );
    }
    return 0;
}

export function doctor(): number {
    info(bold('b doctor'));
    info('');
    let problems = 0;
    const check = (good: boolean, label: string, hint?: string) => {
        if (good) {
            ok(label);
        } else {
            fail(label);
            if (hint) info(`  ${dim(hint)}`);
            problems++;
        }
    };

    const binDir = denoBinDir();
    const binPath = join(binDir, 'b');
    check(exists(binPath), `command shim ${tildify(binPath)}`, 'run `b setup`');
    check(
        onPath(binDir),
        `${tildify(binDir)} on $PATH`,
        'run `b setup`, then `exec zsh`',
    );
    check(
        exists(initFile()),
        `shell integration ${tildify(initFile())}`,
        'run `b setup`',
    );

    const rc = readRc();
    check(
        rc.hasBlock,
        `${tildify(zshrc())} sources the integration`,
        'run `b setup`',
    );

    const ctx = Deno.env.get('B_CTX');
    const wrapped = Deno.env.get('B_FROM_SHELL') === '1';
    check(
        wrapped,
        'shell wrapper active (b can change your directory)',
        'run `exec zsh` — without the wrapper b can only print paths',
    );

    const store = exists(bookmarksFile());
    info(
        store
            ? `${dim('bookmarks:')} ${cyan(tildify(bookmarksFile()))}`
            : `${dim('bookmarks:')} none yet ${dim('(b add)')}`,
    );
    info(
        ctx !== undefined && ctx.length > 0
            ? `${dim('context:')} ${cyan(ctx)}`
            : `${dim('context:')} none active`,
    );

    info('');
    if (problems === 0) info(`${bold('All good.')}`);
    else info(`${problems} problem${problems === 1 ? '' : 's'} found.`);
    return problems === 0 ? 0 : 1;
}
